### ISSUE TITLE
Kotlin，在图片列表直接返回，不选择图片。崩溃了

### ISSUE THREAD

**Issue by mtjsoft** [smuyyh/ImageSelector#129]
“Kotlin中，在图片列表直接返回，不选择图片。崩溃了”
之前#120的问题，忘记回复，被关闭了，抱歉。

**Comment by smuyyh** [comment]
log 能打出来么？

**Comment by mtjsoft** [comment]
等一下，我打印看看。

**Comment by mtjsoft** [comment]
05-11 10:34:35.083 19831-19831/com.lightlock.www.mykotlin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lightlock.www.mykotlin, PID: 19831
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1002, result=0, data=null} to activity {com.lightlock.www.mykotlin/com.lightlock.www.mykotlin.ui.main.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4284)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4327)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6524)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at com.lightlock.www.mykotlin.ui.main.MainActivity.onActivityResult(MainActivity.kt)
        at android.app.Activity.dispatchActivityResult(Activity.java:7188)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4280)

**Comment by smuyyh** [comment]
这是你kotlin本身用法的问题吧..  Intent data后面加个问号，取消非空检查。

**Comment by mtjsoft** [comment]
还真是baseactivity里面的检查导致的。攒+32
