### ISSUE TITLE
红米note4X 7.0 报错

### ISSUE THREAD

**Issue by pengguanming** [smuyyh/ImageSelector#133]
ISCameraConfig config = new ISCameraConfig.Builder()
                .needCrop(false) // 裁剪
                .cropSize(1, 1, 200, 200)
                .build();
        ISNav.getInstance().toCameraActivity(this, config, REQUEST_CAMERA_CODE);

---------------------------------------------------

05-29 16:41:26.328 16011-16011/monster.com.cvh E/AndroidRuntime: FATAL EXCEPTION: main
    Process: monster.com.cvh, PID: 16011
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=5, result=-1, data=null} to activity {monster.com.cvh/com.yuyh.library.imgsel.ui.ISCameraActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4196)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6365)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
        at com.yuyh.library.imgsel.ui.ISCameraActivity.onActivityResult(ISCameraActivity.java:172)
        at android.app.Activity.dispatchActivityResult(Activity.java:7116)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4192)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6365) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) 
05-29 16:41:26.355 16011-16011/monster.com.cvh E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=5, result=-1, data=null} to activity {monster.com.cvh/com.yuyh.library.imgsel.ui.ISCameraActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4196)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6365)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
        at com.yuyh.library.imgsel.ui.ISCameraActivity.onActivityResult(ISCameraActivity.java:172)
        at android.app.Activity.dispatchActivityResult(Activity.java:7116)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4192)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6365) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) 
05-29 16:41:26.817 16011-16011/monster.com.cvh E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Failure delivering result ResultInfo{who=null, request=5, result=-1, data=null} to activity {monster.com.cvh/com.yuyh.library.imgsel.ui.ISCameraActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
05-29 16:41:26.820 16011-16011/monster.com.cvh E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=5, result=-1, data=null} to activity {monster.com.cvh/com.yuyh.library.imgsel.ui.ISCameraActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4196)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6365)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
        at com.yuyh.library.imgsel.ui.ISCameraActivity.onActivityResult(ISCameraActivity.java:172)
        at android.app.Activity.dispatchActivityResult(Activity.java:7116)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4192)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4239) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6365) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:883) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)

**Comment by smuyyh** [comment]
更新到2.0.3？

**Comment by pengguanming** [comment]
更新到2.0.3没问题了。
