### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by 317381081** [smuyyh/ImageSelector#142]
升级之后打不开相机，打开会挂掉

**Comment by smuyyh** [comment]
log贴一下

**Comment by lk27748772** [comment]
升级之后打不开相机，打开会挂掉 ，同问题

**Comment by lk27748772** [comment]
08-13 14:07:20.759 30522-30522/com.fengunion.kdlogistics.company E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fengunion.kdlogistics.company, PID: 30522
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65537, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.fengunion.kdlogistics.company/com.fengunion.kdlogistics.activity.ImgFxSelActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4146)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4189)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6205)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
        at com.yuyh.library.imgsel.ui.fragment.ImgSelFragment.showCameraAction(ImgSelFragment.java:381)
        at com.yuyh.library.imgsel.ui.fragment.ImgSelFragment.onRequestPermissionsResult(ImgSelFragment.java:423)
        at android.support.v4.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:804)
        at com.yuyh.library.imgsel.ui.ISListActivity.onRequestPermissionsResult(ISListActivity.java:273)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7280)
        at android.app.Activity.dispatchActivityResult(Activity.java:7132)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4142)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4189) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163)

**Comment by lk27748772** [comment]
我这边所有手机都会出现这个问题，Android4.0+，7.0+，8.0+

**Comment by jinlinupup** [comment]
+1，我配置了provide后提示Manifest merger failed with multiple errors(清单合并失败)

**Comment by smuyyh** [comment]
好的，马上解决

**Comment by smuyyh** [comment]
compile 'com.yuyh.imgsel:library:2.0.5'

**Comment by jinlinupup** [comment]
OK了~ 谢谢

**Comment by 317381081** [comment]
我在三星note2，系统4.4.2 。拍照裁剪时，图片返回的时候会旋转一定角
度。现自己修改（裁剪前把图片旋转），不知道如何联系你

**Comment by smuyyh** [comment]
@317381081 #76 三星是有这个坑。
