### ISSUE TITLE
拍照报空指针异常

### ISSUE THREAD

**Issue by XxWwCc** [smuyyh/ImageSelector#161]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
        at com.yuyh.library.imgsel.ui.fragment.ImgSelFragment.showCameraAction(ImgSelFragment.java:381)
        at com.yuyh.library.imgsel.ui.fragment.ImgSelFragment.access$200(ImgSelFragment.java:61)
        at com.yuyh.library.imgsel.ui.fragment.ImgSelFragment$1.onImageClick(ImgSelFragment.java:139)
        at com.yuyh.library.imgsel.adapter.ImageListAdapter$1.onClick(ImageListAdapter.java:47)
        at android.view.View.performClick(View.java:6648)
        at android.view.View.performClickInternal(View.java:6620)
        at android.view.View.access$3100(View.java:787)
        at android.view.View$PerformClick.run(View.java:26167)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by smuyyh** [comment]
断点一下 FileUtils.getApplicationId(getActivity()) 的值有没有拿到

**Comment by XxWwCc** [comment]
有的，拿到了

**Comment by XxWwCc** [comment]
选择图片是没有问题的，拍照一点就奔溃了

**Comment by XxWwCc** [comment]
是applicationInfo.metaData 报的空指针

**Comment by XxWwCc** [comment]
applicationInfo也是null

**Comment by smuyyh** [comment]
机型和android版本？

**Comment by XxWwCc** [comment]
刚才找到答案了，是在 AndroidManifest.xml 中加了FileProvider节点，注释掉就行了，但是有个问题，要是其它地方需要这种节点那可能就没法弄了
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"
                tools:replace="android:resource" />
        </provider>

**Comment by XxWwCc** [comment]
荣耀8X 9.0

**Comment by smuyyh** [comment]
源码依赖的？？ FileProvider android:authorities唯一就可以吧。

**Comment by XxWwCc** [comment]
不是源码依赖的，是我自己的项目中依赖的
