### ISSUE TITLE
拍照crash

### ISSUE THREAD

**Issue by zhuangzhitu** [smuyyh/ImageSelector#164]
FATAL EXCEPTION: main
    Process: com.mubu.app.debug, PID: 30949
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mubu.app.debug/com.yuyh.library.imgsel.ui.ISCameraActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.mubu.app.debug/cache/1566709146033.jpg
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3176)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3311)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2051)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7103)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/com.mubu.app.debug/cache/1566709146033.jpg
        at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
        at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
        at com.yuyh.library.imgsel.ui.ISCameraActivity.camera(ISCameraActivity.java:88)
        at com.yuyh.library.imgsel.ui.ISCameraActivity.onCreate(ISCameraActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:7248)
        at android.app.Activity.performCreate(Activity.java:7239)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3156)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3311) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2051) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7103) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by WANG1020** [comment]
android 7.0吗？
