### ISSUE TITLE
1.3.6版本出现严重bug

### ISSUE THREAD

**Issue by feisher** [smuyyh/ImageSelector#40]
本来为了适配7.0做的优化，现在安卓4.4.4和安卓4.2.2发现崩溃现象，回退到1.3.5则没有，希望及时查看一下，miui系统

**Comment by feisher** [comment]
拍照返回出现崩溃

**Comment by feisher** [comment]
java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{43112410 15588:com.android.camera/u0a16} (pid=15588, uid=10016) that is not exported from uid 10131
	at android.os.Parcel.readException(Parcel.java:1489)
	at android.os.Parcel.readException(Parcel.java:1443)
	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:2855)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:4412)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2246)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1447)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:928)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:691)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:667)
	at com.android.camera.module.CameraModule.doAttach(CameraModule.java:2361)
	at com.android.camera.module.CameraModule.onReviewDoneClicked(CameraModule.java:2324)
	at com.android.camera.module.CameraModule.handleMessage(CameraModule.java:1848)
	at com.android.camera.ui.UIController.dispacherMessage(UIController.java:198)
	at com.android.camera.ui.CaptureControlPanel.onClick(CaptureControlPanel.java:43)
	at android.view.View.performClick(View.java:4444)
	at android.view.View$PerformClick.run(View.java:18440)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5016)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by feisher** [comment]
请将清单文件中
 +        <provider
 +            android:name="android.support.v4.content.FileProvider"
 +            android:authorities="com.yuyh.library.imgsel.provider"
 +            android:exported="**_false_**"
 +            android:grantUriPermissions="true">
 +            <meta-data
 +                android:name="android.support.FILE_PROVIDER_PATHS"
 +                android:resource="@xml/provider_paths"/>
 +        </provider>

**## false 改为  true**

**Comment by smuyyh** [comment]
不好意思。之前适配7.0的时候没仔细测，已解决。1.3.7，试试哈~

**Comment by feisher** [comment]
还有个问题，由于此库文件中设置了provider 所以如果开发的两个应用都使用了这个库，就会导致冲突无法同时安装两个应用，麻烦看下有解决办法没

**Comment by smuyyh** [comment]
可能没啥好办法。要嘛就是拉源码下来改，targetSdkVersion 23及以下  就不需要那个provider了好像
