### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Yangzhiwem** [smuyyh/ImageSelector#68]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
	at com.yuyh.library.imgsel.ImgSelFragment.showCameraAction(ImgSelFragment.java:347)
	at com.yuyh.library.imgsel.ImgSelFragment.access$200(ImgSelFragment.java:53)
	at com.yuyh.library.imgsel.ImgSelFragment$1.onImageClick(ImgSelFragment.java:129)
	at com.yuyh.library.imgsel.adapter.ImageListAdapter$1.onClick(ImageListAdapter.java:46)
	at android.view.View.performClick(View.java:4792)
	at android.view.View$PerformClick.run(View.java:19915)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5308)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)

**Comment by smuyyh** [comment]
什么情况下报的？最新版本么？

**Comment by Yangzhiwem** [comment]
已经解决了  是FileProvider冲突
