### ISSUE TITLE
拍照后会包空指针 android6.0

### ISSUE THREAD

**Issue by yuxingfafu** [smuyyh/ImageSelector#69]
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.yuyh.library.imgsel.ImgSelConfig.allImagesText' on a null object reference
                                                                              at com.yuyh.library.imgsel.ImgSelFragment.onViewCreated(ImgSelFragment.java:109)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
                                                                              at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2149)
                                                                              at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:600)
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1246)
                                                                              at android.app.Activity.performStart(Activity.java:6620)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2542)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                              at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                              at android.os.Looper.loop(Looper.java:207) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5770) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by yuxingfafu** [comment]
可以了，发现是少设置了一个参数
                .allImagesText("图片")
