### ISSUE TITLE
Android 7.0手机报空指针

### ISSUE THREAD

**Issue by loandroid** [smuyyh/ImageSelector#82]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                         at android.content.ContextWrapper.getResources(ContextWrapper.java:87)
                                                                         at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:81)
                                                                         at android.support.v7.app.AppCompatActivity.getResources(AppCompatActivity.java:542)
                                                                         at com.yuyh.library.imgsel.ImgSelConfig$Builder.<init>(ImgSelConfig.java:151)

**Comment by smuyyh** [comment]
Context空的。ImageSelConfig 构造的context参数没传吧。

**Comment by smm113522** [comment]
Process: com.iguxuan, PID: 14765
                                                             android.os.FileUriExposedException: file:///storage/emulated/0/Download/u%3D1725541233%2C331749490%26fm%3D173%26app%3D25%26f%3DJPEG.jpg exposed beyond app through Intent.getData()
                                                                 at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
android 7.1.1 出现的问题
